name: MCValorant
version: 0.0.1
api-version: 1.18
author: AV3_08
main: me.av306.mcvalorant.Main
description: Full Valorant logic in Minecraft

commands:    
    mcvalorant:
        description: Main MCValorant command
        usage: /mcvalorant <help | subcommand>